from .core import *
from .profile_commands import *
from .state import *


def _theme_adapter_paths(theme):
    entry = theme_manifest_by_id(theme)
    if not entry:
        return []

    colorschemes = colorscheme_module_dir()
    aggregate_root = os.path.abspath(os.path.join(colorschemes, "..", ".."))
    registry = _load_theme_registry()
    if registry:
        return [
            ("theme", label, str(path))
            for label, path in registry.adapter_paths(
                colorschemes,
                entry,
                aggregate_root=aggregate_root,
            )
        ]

    checks = [
        ("colorscheme manifest", os.path.join(colorschemes, "themes", f"{theme}.toml")),
        ("universal script", os.path.join(colorschemes, "universal", f"{theme}.sh")),
        ("macos script", os.path.join(colorschemes, "macos", f"{theme}.sh")),
        ("arch script", os.path.join(colorschemes, "arch", f"{theme}.sh")),
    ]
    return [("theme", label, path) for label, path in checks]

def _prompt_adapter_paths(prompt):
    profile = prompt_profile_by_id(prompt)
    registry = _load_prompt_registry()
    if not profile or not registry:
        return []

    aggregate_root = os.path.abspath(os.path.join(installer_root, ".."))
    return [
        ("prompt", label, str(path))
        for label, path in registry.adapter_paths(aggregate_root, profile)
    ]

def adapter_paths(theme=None, prompt=None):
    theme = theme or current_theme()
    prompt = prompt or current_prompt()
    return _theme_adapter_paths(theme) + _prompt_adapter_paths(prompt)

def _manifest_file_for_id(manifest_id, search_dirs, registry=None):
    for directory in search_dirs:
        if not os.path.isdir(directory):
            continue
        for filename in sorted(os.listdir(directory)):
            if not filename.endswith(".toml"):
                continue
            path = os.path.join(directory, filename)
            if registry and hasattr(registry, "read_manifest"):
                manifest = registry.read_manifest(path)
            else:
                manifest = _read_simple_toml(path)
            if manifest.get("id") == manifest_id:
                return path
    return None

def _expand_adapter_path(path, source_dir=None):
    expanded = os.path.expanduser(path)
    if os.path.isabs(expanded):
        return expanded
    if source_dir:
        return os.path.abspath(os.path.join(source_dir, expanded))
    return os.path.abspath(expanded)

def _materializable_manifest_entries(kind, manifest_id, manifest, manifest_path):
    if not manifest_path:
        return []

    sources = manifest.get("adapter_sources", {})
    targets = manifest.get("adapter_targets", {})
    modes = manifest.get("adapter_modes", {})
    if not isinstance(sources, dict) or not isinstance(targets, dict):
        return []

    source_dir = os.path.dirname(manifest_path)
    entries = []
    for name, source in sorted(sources.items()):
        target = targets.get(name)
        if not target:
            continue
        mode = modes.get(name, "copy") if isinstance(modes, dict) else "copy"
        entries.append({
            "kind": kind,
            "manifest_id": manifest_id,
            "name": name,
            "mode": mode,
            "source": _expand_adapter_path(source, source_dir),
            "target": _expand_adapter_path(target),
        })
    return entries

def materializable_adapters(theme=None, prompt=None):
    theme = theme or current_theme()
    prompt = prompt or current_prompt()

    theme_manifest = theme_manifest_by_id(theme) or {}
    prompt_manifest = prompt_profile_by_id(prompt) or {}
    theme_manifest_path = _manifest_file_for_id(
        theme,
        (theme_manifests_dir(), theme_catalog_path),
        _load_theme_registry(),
    )
    prompt_manifest_path = _manifest_file_for_id(
        prompt,
        (prompt_profiles_path, prompt_catalog_path),
        _load_prompt_registry(),
    )

    return (
        _materializable_manifest_entries("theme", theme, theme_manifest, theme_manifest_path)
        + _materializable_manifest_entries("prompt", prompt, prompt_manifest, prompt_manifest_path)
    )

def _write_adapter_manifest(entries):
    os.makedirs(adapter_state_path, exist_ok=True)
    with open(adapter_manifest_json_path, "w") as f:
        json.dump(entries, f, indent=2, sort_keys=True)
        f.write("\n")

    with open(adapter_manifest_env_path, "w") as f:
        f.write("# generated by set-me-up; run `smu adapter materialize` to refresh\n")
        f.write(f"export SMU_ADAPTER_MANIFEST_JSON={_shell_quote(adapter_manifest_json_path)}\n")
        f.write(f"export SMU_ADAPTER_COUNT={_shell_quote(len(entries))}\n")
        for index, entry in enumerate(entries):
            prefix = f"SMU_ADAPTER_{index}"
            f.write(f"export {prefix}_KIND={_shell_quote(entry['kind'])}\n")
            f.write(f"export {prefix}_NAME={_shell_quote(entry['name'])}\n")
            f.write(f"export {prefix}_MODE={_shell_quote(entry['mode'])}\n")
            f.write(f"export {prefix}_SOURCE={_shell_quote(entry['source'])}\n")
            f.write(f"export {prefix}_TARGET={_shell_quote(entry['target'])}\n")

def _read_adapter_manifest():
    if not os.path.exists(adapter_manifest_json_path):
        return []
    try:
        with open(adapter_manifest_json_path) as f:
            data = json.load(f)
        if isinstance(data, list):
            return data
    except (json.JSONDecodeError, IOError, OSError) as e:
        warn(f"Could not read adapter manifest '{adapter_manifest_json_path}': {e}")
    return []

def _adapter_target_conflicts(entry):
    target = entry["target"]
    if not os.path.lexists(target):
        return False
    snapshot = file_snapshot(target)
    if snapshot.get("type") == "symlink" and snapshot.get("link_target") == entry["source"]:
        return False
    source_hash = file_sha256(entry["source"])
    target_hash = file_sha256(target)
    return not (source_hash and target_hash and source_hash == target_hash)


def materialize_adapters(theme=None, prompt=None, dry_run=False, force=False):
    entries = materializable_adapters(theme, prompt)
    state_items = []
    for entry in entries:
        source = entry["source"]
        target = entry["target"]
        mode = entry["mode"]
        if dry_run:
            print(f"{mode}\t{source}\t{target}")
            continue
        if not os.path.exists(source):
            die(f"Adapter source does not exist: {source}")
        if not force and _adapter_target_conflicts(entry):
            die(f"Adapter target has unmanaged content: {target}. Use --force to overwrite.")
        os.makedirs(os.path.dirname(target), exist_ok=True)
        state_items.append({
            "kind": entry["kind"],
            "manifest_id": entry["manifest_id"],
            "name": entry["name"],
            "target": target,
            "before": file_snapshot(target),
        })
        if mode == "symlink":
            tmp_target = os.path.join(os.path.dirname(target), f".{os.path.basename(target)}.tmp")
            if os.path.lexists(tmp_target):
                os.unlink(tmp_target)
            os.symlink(source, tmp_target)
            os.replace(tmp_target, target)
        elif mode == "copy":
            fd, tmp_target = tempfile.mkstemp(prefix=f".{os.path.basename(target)}.", dir=os.path.dirname(target))
            os.close(fd)
            try:
                shutil.copy2(source, tmp_target)
                os.replace(tmp_target, target)
            finally:
                if os.path.exists(tmp_target):
                    os.unlink(tmp_target)
        else:
            die(f"Unsupported adapter materialization mode '{mode}' for {entry['name']}")

    if not dry_run:
        _write_adapter_manifest(entries)
        record_state_event("materialize_adapters", state_items)
        success(f"Materialized {len(entries)} adapter(s)")
    return entries

def handle_adapter_command(argv):
    command = argv[0] if argv else "list"
    if command == "list":
        theme = current_theme()
        prompt = current_prompt()
        if len(argv) > 1:
            theme = argv[1]
        if len(argv) > 2:
            prompt = argv[2]
        for kind, label, path in adapter_paths(theme, prompt):
            status = "present" if os.path.exists(path) else "missing"
            print(f"{kind}\t{label}\t{status}\t{path}")
        return

    if command == "doctor":
        theme = argv[1] if len(argv) > 1 else current_theme()
        prompt = argv[2] if len(argv) > 2 else current_prompt()
        raise SystemExit(adapter_doctor(theme, prompt))

    if command == "materialize":
        dry_run = "--dry-run" in argv[1:]
        force = "--force" in argv[1:]
        positional = [arg for arg in argv[1:] if not arg.startswith("--")]
        theme = positional[0] if len(positional) > 0 else current_theme()
        prompt = positional[1] if len(positional) > 1 else current_prompt()
        materialize_adapters(theme, prompt, dry_run=dry_run, force=force)
        return

    if command == "install":
        theme = argv[1] if len(argv) > 1 else current_theme()
        prompt = argv[2] if len(argv) > 2 else current_prompt()
        if theme not in supported_themes():
            die(f"Unknown theme '{theme}'. Valid values: {', '.join(supported_themes())}")
        if prompt not in supported_prompts():
            die(f"Unknown prompt '{prompt}'. Valid values: {', '.join(supported_prompts())}")
        set_profile_value("SMU_THEME", theme, supported_themes())
        set_profile_value("SMU_PROMPT", prompt, supported_prompts())
        provision_module("colorschemes")
        write_resolved_profile()
        success(f"Installed adapters for theme={theme}, prompt={prompt}")
        return

    if command == "init":
        if len(argv) < 2:
            die("Usage: smu adapter init <id> [--force]")
        _init_adapter(argv[1], force="--force" in argv[2:])
        return

    die("Usage: smu adapter [list [theme] [prompt]|doctor [theme] [prompt]|materialize [theme] [prompt] [--dry-run] [--force]|install [theme] [prompt]|init <id>]")

def adapter_doctor(theme=None, prompt=None):
    theme = theme or current_theme()
    prompt = prompt or current_prompt()
    failed = False

    if theme not in supported_themes():
        failed = True
        print(f"{COL_RED}FAIL{COL_RESET} unknown theme {theme}")
    if prompt not in supported_prompts():
        failed = True
        print(f"{COL_RED}FAIL{COL_RESET} unknown prompt {prompt}")

    paths = adapter_paths(theme, prompt)
    if not paths:
        failed = True
        print(f"{COL_RED}FAIL{COL_RESET} no adapters resolved")

    for kind, label, path in paths:
        if os.path.exists(path):
            print(f"{COL_GREEN}OK{COL_RESET}   {kind} {label}")
        else:
            failed = True
            print(f"{COL_RED}MISS{COL_RESET} {kind} {label}: {path}")

    for entry in materializable_adapters(theme, prompt):
        if os.path.exists(entry["source"]):
            print(f"{COL_GREEN}OK{COL_RESET}   {entry['kind']} materialize source {entry['name']}")
        else:
            failed = True
            print(f"{COL_RED}MISS{COL_RESET} {entry['kind']} materialize source {entry['name']}: {entry['source']}")

    for entry in _read_adapter_manifest():
        target = entry.get("target")
        label = entry.get("name", "<unknown>")
        kind = entry.get("kind", "adapter")
        if target and os.path.exists(target):
            print(f"{COL_GREEN}OK{COL_RESET}   {kind} materialized target {label}")
        elif target:
            failed = True
            print(f"{COL_RED}MISS{COL_RESET} {kind} materialized target {label}: {target}")

    return 1 if failed else 0


__all__ = [name for name in globals() if not name.startswith("__")]
